on:
  push:
    branches:
      - master

name: Deploy service
jobs:
  deploy:
    runs-on: self-hosted #${{matrix.os}} to reduce billing
    steps:
    - uses: actions/checkout@master
    - name: deploy
      uses: ./.github/action-deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
